<template>
	<view class="icon">
		<u-grid :col="3">
			<block v-for="(item, index) in list" :key="index">
				<!-- <u-grid-item v-if="item.count == 1"><u-icon :name="item.name" :size="46"></u-icon></u-grid-item> -->

				<u-grid-item><u-icon :name="item.name" label-color="#edd342" :label="item.name" :size="40"></u-icon></u-grid-item>
			</block>
		</u-grid>
	</view>
</template>

<script>
export default {
	data() {
		return {
			list: [
				{ name: 'arrow-left-double', count: 1 },
				{ name: 'arrow-right-double', count: 0 },
				{ name: 'chat', count: 0 },
				{ name: 'chat-fill', count: 0 },
				{ name: 'red-packet', count: 0 },
				{ name: 'red-packet-fill', count: 0 },
				{ name: 'order', count: 0 },
				{ name: 'checkbox-mark', count: 0 },
				{ name: 'arrow-up-fill', count: 0 },
				{ name: 'arrow-down-fill', count: 0 },
				{ name: 'backspace', count: 0 },
				{ name: 'photo', count: 0 },
				{ name: 'photo-fill', count: 0 },
				{ name: 'lock', count: 0 },
				{ name: 'lock-fill', count: 0 },
				{ name: 'lock-open', count: 0 },
				{ name: 'lock-opened-fill', count: 0 },
				{ name: 'hourglass', count: 0 },
				{ name: 'hourglass-half-fill', count: 0 },
				{ name: 'home', count: 0 },
				{ name: 'home-fill', count: 0 },
				{ name: 'fingerprint', count: 0 },
				{ name: 'cut', count: 0 },
				{ name: 'star', count: 0 },
				{ name: 'star-fill', count: 0 },
				{ name: 'share', count: 0 },
				{ name: 'share-fill', count: 0 },
				{ name: 'volume-up', count: 0 },
				{ name: 'volume-up-fill', count: 0 },
				{ name: 'volume-off', count: 0 },
				{ name: 'volume-off-fill', count: 0 },
				{ name: 'trash', count: 0 },
				{ name: 'trash-fill', count: 0 },
				{ name: 'rewind-right', count: 0 },
				{ name: 'rewind-right-fill', count: 0 },
				{ name: 'rewind-left', count: 0 },
				{ name: 'rewind-left-fill', count: 0 },
				{ name: 'shopping-cart', count: 0 },
				{ name: 'shopping-cart-fill', count: 0 },
				{ name: 'question', count: 0 },
				{ name: 'question-circle', count: 0 },
				{ name: 'question-circle-fill', count: 0 },
				{ name: 'plus', count: 0 },
				{ name: 'plus-circle', count: 0 },
				{ name: 'plus-circle-fill', count: 0 },
				{ name: 'tags', count: 0 },
				{ name: 'tags-fill', count: 0 },
				{ name: 'pause', count: 0 },
				{ name: 'pause-circle', count: 0 },
				{ name: 'pause-circle-fill', count: 0 },
				{ name: 'play-circle', count: 0 },
				{ name: 'play-circle-fill', count: 0 },
				{ name: 'map', count: 0 },
				{ name: 'map-fill', count: 0 },
				{ name: 'phone', count: 0 },
				{ name: 'phone-fill', count: 0 },
				{ name: 'list', count: 0 },
				{ name: 'list-dot', count: 0 },
				{ name: 'man-delete', count: 0 },
				{ name: 'man-add', count: 0 },
				{ name: 'man-add-fill', count: 0 },
				{ name: 'person-delete-fill', count: 0 },
				{ name: 'info', count: 0 },
				{ name: 'info-circle', count: 0 },
				{ name: 'info-circle-fill', count: 0 },
				{ name: 'minus', count: 0 },
				{ name: 'minus-circle', count: 0 },
				{ name: 'minus-circle-fill', count: 0 },
				{ name: 'mic', count: 0 },
				{ name: 'mic-off', count: 0 },
				{ name: 'grid', count: 0 },
				{ name: 'grid-fill', count: 0 },
				{ name: 'eye', count: 0 },
				{ name: 'eye-fill', count: 0 },
				{ name: 'eye-fill', count: 0 },
				{ name: 'file-text', count: 0 },
				{ name: 'file-text-fill', count: 0 },
				{ name: 'edit-pen', count: 0 },
				{ name: 'edit-pen-fill', count: 0 },
				{ name: 'email', count: 0 },
				{ name: 'email-fill', count: 0 },
				{ name: 'download', count: 0 },
				{ name: 'checkmark', count: 0 },
				{ name: 'checkmark-circle', count: 0 },
				{ name: 'checkmark-circle-fill', count: 0 },
				{ name: 'clock', count: 0 },
				{ name: 'clock-fill', count: 0 },
				{ name: 'close', count: 0 },
				{ name: 'close-circle', count: 0 },
				{ name: 'close-circle-fill', count: 0 },
				{ name: 'calendar', count: 0 },
				{ name: 'calendar-fill', count: 0 },
				{ name: 'car', count: 0 },
				{ name: 'car-fill', count: 0 },
				{ name: 'bell', count: 0 },
				{ name: 'bell-fill', count: 0 },
				{ name: 'bookmark', count: 0 },
				{ name: 'bookmark-fill', count: 0 },
				{ name: 'attach', count: 0 },
				{ name: 'play-right', count: 0 },
				{ name: 'play-right-fill', count: 0 },
				{ name: 'play-left', count: 0 },
				{ name: 'play-left-fill', count: 0 },
				{ name: 'error', count: 0 },
				{ name: 'error-circle', count: 0 },
				{ name: 'error-circle-fill', count: 0 },
				{ name: 'wifi', count: 0 },
				{ name: 'wifi-off', count: 0 },
				{ name: 'skip-back-left', count: 0 },
				{ name: 'skip-forward-right', count: 0 },
				{ name: 'search', count: 0 },
				{ name: 'setting', count: 0 },
				{ name: 'setting-fill', count: 0 },
				{ name: 'volume', count: 0 },
				{ name: 'volume-fill', count: 0 },
				{ name: 'more-dot-fill', count: 0 },
				{ name: 'more-circle', count: 0 },
				{ name: 'more-circle-fill', count: 0 },
				{ name: 'bag', count: 0 },
				{ name: 'bag-fill', count: 0 },
				{ name: 'arrow-upward', count: 0 },
				{ name: 'arrow-downward', count: 0 },
				{ name: 'arrow-leftward', count: 0 },
				{ name: 'arrow-rightward', count: 0 },
				{ name: 'arrow-up', count: 0 },
				{ name: 'arrow-down', count: 0 },
				{ name: 'arrow-left', count: 0 },
				{ name: 'arrow-right', count: 0 },
				{ name: 'rmb', count: 0 },
				{ name: 'rmb-circle', count: 0 },
				{ name: 'rmb-circle-fill', count: 0 },
				{ name: 'thumb-up', count: 0 },
				{ name: 'thumb-up-fill', count: 0 },
				{ name: 'thumb-down', count: 0 },
				{ name: 'thumb-down-fill', count: 0 },
				{ name: 'coupon', count: 0 },
				{ name: 'coupon-fill', count: 0 },
				{ name: 'kefu-ermai', count: 0 },
				{ name: 'server-fill', count: 0 },
				{ name: 'server-man', count: 0 },
				{ name: 'scan', count: 0 },
				{ name: 'warning', count: 0 },
				{ name: 'warning-fill', count: 0 },
				{ name: 'google', count: 0 },
				{ name: 'google-circle-fill', count: 0 },
				{ name: 'chrome-circle-fill', count: 0 },
				{ name: 'ie', count: 0 },
				{ name: 'IE-circle-fill', count: 0 },
				{ name: 'github-circle-fill', count: 0 },
				{ name: 'android-fill', count: 0 },
				{ name: 'android-circle-fill', count: 0 },
				{ name: 'apple-fill', count: 0 },
				{ name: 'camera', count: 0 },
				{ name: 'camera-fill', count: 0 },
				{ name: 'pushpin', count: 0 },
				{ name: 'pushpin-fill', count: 0 },
				{ name: 'minus-square-fill', count: 0 },
				{ name: 'plus-square-fill', count: 0 },
				{ name: 'heart', count: 0 },
				{ name: 'heart-fill', count: 0 },
				{ name: 'reload', count: 0 },
				{ name: 'account', count: 0 },
				{ name: 'account-fill', count: 0 },
				{ name: 'minus-people-fill', count: 0 },
				{ name: 'plus-people-fill', count: 0 },
				{ name: 'integral', count: 0 },
				{ name: 'integral-fill', count: 0 },
				{ name: 'zhihu', count: 0 },
				{ name: 'zhihu-circle-fill', count: 0 },
				{ name: 'gift', count: 0 },
				{ name: 'gift-fill', count: 0 },
				{ name: 'zhifubao', count: 0 },
				{ name: 'zhifubao-circle-fill', count: 0 },
				{ name: 'weixin-fill', count: 0 },
				{ name: 'weixin-circle-fill', count: 0 },
				{ name: 'twitter', count: 0 },
				{ name: 'twitter-circle-fill', count: 0 },
				{ name: 'taobao', count: 0 },
				{ name: 'taobao-circle-fill', count: 0 },
				{ name: 'weibo', count: 0 },
				{ name: 'weibo-circle-fill', count: 0 },
				{ name: 'qq-fill', count: 0 },
				{ name: 'qq-circle-fill', count: 0 },
				{ name: 'moments', count: 0 },
				{ name: 'moments-circel-fill', count: 0 },
				{ name: 'qzone', count: 0 },
				{ name: 'qzone-circle-fill', count: 0 },
				{ name: 'facebook', count: 0 },
				{ name: 'facebook-circle-fill', count: 0 },
				{ name: 'baidu', count: 0 },
				{ name: 'baidu-circle-fill', count: 0 },
				{ name: 'zhuanfa', count: 0 }
			]
		};
	},
	onLoad(e) {
		uni.setNavigationBarTitle({
			title: e.option
		});
	}
};
</script>

<style lang="scss">
.icon {
	width: 100%;
	height: 100%;
}
</style>
